config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:  "items#index"
  resources :items, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '使用感がなく良好な状態' },
    { id: 3, name: '使用感はあるが、まだまだ使用可能' },
    { id: 4, name: '使用可能だが、汚れ・キズ等が目立つ' }
  ]

    include ActiveHash::Associations
    has_many :items

  end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :condition
  belongs_to :receive
  has_one_attached :image
  
  validates :condition_id, numericality: { other_than: 1 } 
  validates :condition_id, numericality: { other_than: 1 , message: "can't be blank"}
  validates :receive_id, numericality: { other_than: 1 } 
  validates :receive_id, numericality: { other_than: 1 , message: "can't be blank"}
end

app/models/receive.rb
class Receive < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '現地での受け取り' },
    { id: 3, name: '自宅まで持ってきてほしい' },
  ]

    include ActiveHash::Associations
    has_many :items

  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    Item.create(item_params)
  end

  private
  def item_params
    params.require(:item).permit(:name, :image, :text, :condition_id, :receive_id).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>出品が完了しました。</h3>
    <a class="btn" href="/">出品一覧へ戻る</a>
  </div>
</div>

app/views/items/index.html.erb
<div class="contents row">
  <% @items.each do |item| %>
    <div class="content_post" >
      <p><%= item.text %></p>
      <span class="name">
        <%= item.name %>
      </span>
      <%= image_tag item.image, class: 'item-image' if item.image.attached? %>
    </div>
  <% end %>
</div>

app/views/items/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>出品する</h3>
    <%= form_with(model: @item, local: true) do |form| %>
      <div class="weight-bold-text">
          <span class="indispensable">Nickname</span>
          <%= form.text_field :name, placeholder: "<必須>" %>
      </div>
      <div class="weight-bold-text">
          <span class="indispensable">クリックしてファイルをアップロード</span>
          <%= form.file_field :image, id:"item-image" %>
      </div>
      <div class="weight-bold-text">
          <span class="indispensable">商品について</span>
          <%= form.text_area :text, placeholder: "<必須>", rows: "10" %>
      </div>
      <div class="weight-bold-text">
          <span class="indispensable">状態</span>
         <%= form.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"genre-select"}) %>
      </div>
      <div class="weight-bold-text">
          <span class="indispensable">受け取り方法</span>
          <%= form.collection_select(:receive_id, Receive.all, :id, :name, {}, {class:"genre-select"}) %>
      </div>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReuseApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/"> Let's リユース</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            <%= link_to "出品", new_item_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright Let's リユース 2019.
      </p>
    </footer>
  </body>
</html>